# Generated by Django 5.0.7 on 2024-07-27 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature2',
            name='username',
        ),
        migrations.AddField(
            model_name='feature2',
            name='points',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='feature2',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
